const NOVA_SCOTIA_CITIES = [
  'Amherst',
  'Annapolis Royal',
  'Antigonish',
  'Baddeck',
  'Bedford',
  'Berwick',
  'Bridgewater',
  'Chéticamp',
  "Clark's Harbour",
  'Cole Harbour',
  'Dartmouth',
  'Digby',
  'Eastern Passage',
  'Elmsdale',
  'Enfield',
  'Eskasoni',
  'Fall River',
  'Glace Bay',
  'Halifax',
  'Hantsport',
  'Herring Cove',
  'Inverness',
  'Kentville',
  "L'Ardoise",
  'Liverpool',
  'Lockeport',
  'Louisbourg',
  'Lower Sackville',
  'Lunenburg',
  'Mahone Bay',
  'Middleton',
  'Mulgrave',
  'New Glasgow',
  'New Minas',
  'North Sydney',
  'Oxford',
  'Parrsboro',
  'Pictou',
  'Port Hawkesbury',
  'Port Hood',
  'River Hebert',
  'Sackville',
  'Shelburne',
  'Sheet Harbour',
  'Sherbrooke',
  'Springhill',
  'Stellarton',
  'Sydney',
  'Sydney Mines',
  'Tatamagouche',
  'Timberlea',
  'Trenton',
  'Truro',
  'Waverley',
  'Westville',
  'Windsor',
  'Wolfville',
  'Yarmouth',
];

module.exports = NOVA_SCOTIA_CITIES;
